language: python

python:
  - "3.5"

services:
  - postgresql

install:
  - pip install tg.devtools
  - pip install .
  - pip install -r requirements.txt

before_script:
  - psql -c "alter user postgres with encrypted password '1234'; create database ave_test;" -U postgres

script: coverage run --source ave $(which nosetests)

