language: python

sudo: required

python:
  - "3.5"

services:
  - postgresql

install:
  - pip install tg.devtools
  - pip install .
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database ave_test;' -U postgres

script: coverage run --source ave $(which nosetests)

after_success: coveralls
